// <auto-generated />
using System;
using MediAssist.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediaAssist.Api.Migrations
{
    [DbContext(typeof(MediAssistDbContext))]
    partial class MediAssistDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediAssist.Api.Data.Entities.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OpenFDAId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("MediAssist.Api.Data.Entities.DrugInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DrugAId")
                        .HasColumnType("integer");

                    b.Property<int>("DrugBId")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DrugBId");

                    b.HasIndex("DrugAId", "DrugBId")
                        .IsUnique();

                    b.ToTable("DrugInteractions");
                });

            modelBuilder.Entity("MediAssist.Api.Data.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicalRecordNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MedicalRecordNumber")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MediAssist.Api.Data.Entities.Symptom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlwaysCritical")
                        .HasColumnType("boolean");

                    b.Property<int>("DefaultSeverityScore")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Symptoms");
                });

            modelBuilder.Entity("MediAssist.Api.Data.Entities.TriageAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PerformedById")
                        .HasColumnType("integer");

                    b.Property<int>("PerformedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PerformedById");

                    b.ToTable("TriageAssessments");
                });

            modelBuilder.Entity("MediAssist.Api.Data.Entities.TriageAssessmentSymptom", b =>
                {
                    b.Property<int>("TriageAssessmentId")
                        .HasColumnType("integer");

                    b.Property<int>("SymptomId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.HasKey("TriageAssessmentId", "SymptomId");

                    b.HasIndex("SymptomId");

                    b.ToTable("TriageAssessmentSymptoms");
                });

            modelBuilder.Entity("MediAssist.Api.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MediAssist.Api.Data.Entities.DrugInteraction", b =>
                {
                    b.HasOne("MediAssist.Api.Data.Entities.Drug", "DrugA")
                        .WithMany("InteractionAsA")
                        .HasForeignKey("DrugAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MediAssist.Api.Data.Entities.Drug", "DrugB")
                        .WithMany("InteractionAsB")
                        .HasForeignKey("DrugBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DrugA");

                    b.Navigation("DrugB");
                });

            modelBuilder.Entity("MediAssist.Api.Data.Entities.Patient", b =>
                {
                    b.HasOne("MediAssist.Api.Data.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("MediAssist.Api.Data.Entities.TriageAssessment", b =>
                {
                    b.HasOne("MediAssist.Api.Data.Entities.Patient", "Patient")
                        .WithMany("Assessments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediAssist.Api.Data.Entities.User", "PerformedBy")
                        .WithMany("Assessments")
                        .HasForeignKey("PerformedById");

                    b.Navigation("Patient");

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("MediAssist.Api.Data.Entities.TriageAssessmentSymptom", b =>
                {
                    b.HasOne("MediAssist.Api.Data.Entities.Symptom", "Symptom")
                        .WithMany()
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediAssist.Api.Data.Entities.TriageAssessment", "Assessment")
                        .WithMany("ObservedSymptoms")
                        .HasForeignKey("TriageAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Symptom");
                });

            modelBuilder.Entity("MediAssist.Api.Data.Entities.Drug", b =>
                {
                    b.Navigation("InteractionAsA");

                    b.Navigation("InteractionAsB");
                });

            modelBuilder.Entity("MediAssist.Api.Data.Entities.Patient", b =>
                {
                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("MediAssist.Api.Data.Entities.TriageAssessment", b =>
                {
                    b.Navigation("ObservedSymptoms");
                });

            modelBuilder.Entity("MediAssist.Api.Data.Entities.User", b =>
                {
                    b.Navigation("Assessments");
                });
#pragma warning restore 612, 618
        }
    }
}
